### ISSUE TITLE
Problems on M1

### ISSUE THREAD

**Issue by dc361** [snappy46/Pivos-Firmware-Install-Addon#3]
Hi Snappy46 - Thanks for the addon!

I have a couple of M1 units here so I backed one up this morning and was going to put the addon to the test.    I installed the latest version (1.1.0) which you uploaded on 2016-01-18.   I configured the addon to select the M1 and noticed that it had pre-selected SDCard as a destination so I did not change this value before hitting "OK".   

When I ran the addon I was prompted for the version to use and then the script threw an error and said to check the log file for more details.   The log file shows:

11:19:09 T:1350808608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (30, 'Read-only file system', '/update.img')
                                            Traceback (most recent call last):

As you can see the script was trying to write update.img to the root directory.   When I noticed this I went back into configuration for the app and manually selected the location of SDCard which then allows the script to get a bit further (starting to download the image from PIVOS) and then throws another error:

11:49:11 T:1316369440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (28, 'No space left on device')
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/script.module.firmware.update/main.py", line 215, in <module>
                                                firmwareUpdate(firmwareArray[ret])
                                              File "/root/.kodi/addons/script.module.firmware.update/main.py", line 179, in firmwareUpdate
                                                DownloaderClass(linkArray[ret], downloadFile)
                                              File "/root/.kodi/addons/script.module.firmware.update/main.py", line 80, in DownloaderClass
                                                urllib.urlretrieve(url, dest, lambda nb, bs, fs, url=url: _pbhook(nb, bs, fs, url, dp))
                                              File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
                                              File "/usr/lib/python2.7/urllib.py", line 272, in retrieve
                                            IOError: (28, 'No space left on device')
                                            -->End of Python script error report<--

The retrieve code seems to be storing the image to /recovery and not /media/sdcard and the recovery partition on an M1 is only 64MB:

/dev/mtdblock3           63.9M     63.6M    332.0K  99% /recovery
tmpfs                   179.7M      6.0M    173.7M   3% /media
tmpfs                   179.7M      6.0M    173.7M   3% /etc
/dev/cardblksd1          14.6G      3.2G     11.4G  22% /media/sdcard

To recover I have to remove the partial image from /recovery and reboot into recovery to clear the cache..

Let me know if you require further information or testing (dc1 on the pivos forum)

**Comment by snappy46** [comment]
Thank you for the complete report.  Could you try to issue this command on your Pivos DS M1 (ssh)with your Sdcard mounted and let me know the results:

df | grep '"/dev/cardblksd1"' | grep -oE '[^ ]+$'

Thank you.

**Comment by dc361** [comment]
The command returns no output but df | grep /dev/cardblksd1 | grep  -oE '[^ ]+$'
returns: 

/media/sdcard
/tmp/userdata
/root
/etc/NetworkManager
/etc/dropbear

Or without the formatting removed: 

/dev/cardblksd1          14.6G      3.2G     11.4G  22% /media/sdcard
/dev/cardblksd1          14.6G      3.2G     11.4G  22% /tmp/userdata
/dev/cardblksd1          14.6G      3.2G     11.4G  22% /root
/dev/cardblksd1          14.6G      3.2G     11.4G  22% /etc/NetworkManager
/dev/cardblksd1          14.6G      3.2G     11.4G  22% /etc/dropbear

**Comment by snappy46** [comment]
That is very strange this command works fine on my XS or my PC for that matter to report only the location of the mount location for /dev/cardblksd1.  This command should only return /media/sdcard in your case??? Maybe the DS M1 has a different kernel/busybox version???  XS has BusyBox v1.22.1 what does the DS M1 has???  Also in order to use the addon your firmware must be already at 80115 or later.

I don't know how much experience you have with linux but if you can figure out the command to use to get only the /dev/cardblksd1 mount location on the DS M1 could you let me know what you use.  I think that the issue is with the linux command not the python code.  Just to be on the safe side of things however I will set a default value to some of the selection items in the settings to try to resolve your original issue before you made a selection.

Thanks again your feedback is appreciated.

**Comment by dc361** [comment]
Are we seeing some sort of ascii code page issue?   If I run the above command on my XS running GIT:2015-11-20, I get no output just like my DS running the same version.  Both boxes are running BusyBox v1.22.1.  If I use the command:

df | grep "/dev/cardblksd1" | grep -oE '[^ ]+$'

I get:

/media/sdcard
/tmp/userdata
/root
/etc/NetworkManager
/etc/dropbear

Which is identical to the DS.  If I check fstab for cardblksd1 I think it will return what you want.  I see:

/dev/cardblksd1 /media/sdcard   vfat    rw,sync 0       0

on both the XS and the DS.   If I use mount, I see all of the above with their attributes.   I think that this may be the result of the tofu-data substitution.

I have also checked the S94tofu-pre scripts on both and neither have any mounts or redirects...

**Comment by dc361** [comment]
Ok .. just tried the script on the DS M1 again and it is still trying to download the image.img file to /recovery which is not large enough on the M1 (only 64 megabytes) so the download fails after about 40 percent.   I then have to manually clear the download from /recovery/image.img and reboot into recovery so I can clear the cache (The cache clear doesn't make sense, but it works)

**Comment by snappy46** [comment]
Sorry the first command I gave you was copied from the code and is wrong unless used in the code to differentiate between literal strings and variables in the code.  The command should be:

This:  df | grep "/dev/cardblksd1" | grep -oE '[^ ]+$'
OR
This:  df | grep '/dev/cardblksd1' | grep -oE '[^ ]+$'
OR
This:  df | grep /dev/cardblksd1 | grep -oE '[^ ]+$'

You already issued the first command with results different than what I am getting????  On my XS when I issue any of these commands it only returns: /media/sdcard   nothing else.  I have no idea why your output is different than mine. The first grep should only return the line that contain /dev/cardblksd1 not the other ones .....  ???? and the second grep only return the last string before the space. Sorry but I can not duplicate error over here.

**Comment by dc361** [comment]
I have no idea why the command returns all three .. perhaps we need to bounce this to Martin or aasoror to get the official answer.

It does appear that firmwareDownloadLocation() is returning 0 for the M1 as the image is /recovery/update.img

I'm in eastern Canada, why don't you set your locale to be the same and see if it returns the same information.   I've tried 2 different M1 units and 2 XS with the same result.

If you need to ssh into my DS, that could be arranged as well -- what timezone are you in (for scheduling)?

**Comment by snappy46** [comment]
Thank you so much for your help; you allowed me to open my eyes and see the logical error in the code.  I know why it returns 0; I'll fix the code and let you know when it's good.  That being said it does not explain the issue with the "df grep" command combo.  Anyway just let me fix the code first then will see if it works.

By the way I am also in eastern Canada (Ontario near Barrie) so same locale set as you already.

**Comment by snappy46** [comment]
Fix done should work ok on the DS M1 now ... well hopefully.  I will close issue once you confirm that latest version works fine.   Simply add +1 for the DS M1 storage location selection; since no cache is available.

**Comment by snappy46** [comment]
Hold on tight there might still be an issue I am mixing String with integer here thanks to python lack of data type ... Arrgh!!!!  Can not fix right now.

**Comment by dc361** [comment]
LoL .. I just tripped over that error.  Sorry I haven't been much help with the python code but I'm VERY rusty with python..   

I'm actually in AST (PEI) but at least in the neighbourhood ...

For completeness, here's the error:

T:1269879840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                   Error Type: <type 'exceptions.TypeError'>
                                   Error Contents: cannot concatenate 'str' and 'int' objects
                                   Traceback (most recent call last):
                                     File "/root/.kodi/addons/script.module.firmware.update/main.py", line 215, in 

<<< SNIP >>>

**Comment by snappy46** [comment]
Sorry about that I should have tested properly first.   I am at work right now so I can not fix the code it but if you replace the line 215 with the line below in main.py it should work:

return str(int(Addon().getSetting('DSM1storage')) + 1)

No need to be sorry you've help me plenty.  I'll make the changes tonight when I have a chance.  By the way PEI is a beautiful area; was there on a few occassions on vacations when I lived in Nova Scotia.

**Comment by dc361** [comment]
Closer... 

 Error Contents: (2, 'No such file or directory', '/media/sdcard/tmp/userdata/root/etc/NetworkManager/etc/dropbear/update.img'

Looks like it is concatenating that whole mess it returns on my DS.  Is there a way to change the regex to return the first line only? 

How about:

 df | grep "/dev/cardblksd1" | grep -oE '[^ ]+$' | head -n1

Turns out a blank SDcard has this:

[root@pivos-m1 ~]# df
Filesystem                Size      Used Available Use% Mounted on
/dev/root               255.8M    173.3M     82.5M  68% /
devtmpfs                179.6M         0    179.6M   0% /dev
tmpfs                   179.7M         0    179.7M   0% /dev/shm
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
/dev/loop0              107.9M    107.9M         0 100% /usr
/dev/mtdblock3           63.9M     24.1M     39.9M  38% /recovery
tmpfs                   179.7M      6.0M    173.7M   3% /media
tmpfs                   179.7M      6.0M    173.7M   3% /etc
/dev/cardblksd1          14.5G    128.0K     14.5G   0% /media/sdcard
/dev/mtdblock4            1.7G     73.9M      1.6G   4% /tmp/userdata
/dev/mtdblock4            1.7G     73.9M      1.6G   4% /root
/dev/mtdblock4            1.7G     73.9M      1.6G   4% /etc/NetworkManager
/dev/mtdblock4            1.7G     73.9M      1.6G   4% /etc/dropbear

If you create a tofu-data directory (only change) and reboot I get the following:

[root@pivos-m1 ~]# df

Filesystem                Size      Used Available Use% Mounted on
/dev/root               255.8M    173.3M     82.5M  68% /
devtmpfs                179.6M         0    179.6M   0% /dev
tmpfs                   179.7M         0    179.7M   0% /dev/shm
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
tmpfs                   179.7M      6.0M    173.7M   3% /tmp
/dev/loop0              107.9M    107.9M         0 100% /usr
/dev/mtdblock3           63.9M     24.1M     39.9M  38% /recovery
tmpfs                   179.7M      6.0M    173.7M   3% /media
tmpfs                   179.7M      6.0M    173.7M   3% /etc
/dev/cardblksd1          14.5G     50.3M     14.4G   0% /media/sdcard
/dev/cardblksd1          14.5G     50.3M     14.4G   0% /tmp/userdata
/dev/mtdblock4            1.7G     78.2M      1.6G   5% /tmp/userdata.internal
/dev/mtdblock4            1.7G     78.2M      1.6G   5% /tmp/userdata/xios/root/.kodi/temp
/dev/cardblksd1          14.5G     50.3M     14.4G   0% /root
/dev/mtdblock4            1.7G     78.2M      1.6G   5% /root/.kodi/temp
/dev/cardblksd1          14.5G     50.3M     14.4G   0% /etc/NetworkManager
/dev/cardblksd1          14.5G     50.3M     14.4G   0% /etc/dropbear

[root@pivos-m1 ~]# cd /media/sdcard
[root@pivos-m1 sdcard]# du -sk *
96      System Volume Information
51392   tofu-data
[root@pivos-m1 sdcard]#

[root@pivos-m1 ~]#  df | grep "/dev/cardblksd1" | grep -oE '[^ ]+$'
/media/sdcard
/tmp/userdata
/root
/etc/NetworkManager
/etc/dropbear

[root@pivos-m1 ~]# df | grep "/dev/cardblksd1" | grep -oE '[^ ]+$' | head -n1
/media/sdcard

**Comment by dc361** [comment]
Ok .. Your string/int fix plus the " | head -n1" worked.   The image downloaded to /media/sdcard, passed MD5 check, rebooted into recovery and flashed properly.

**Comment by snappy46** [comment]
Ok this:
df | grep /dev/cardblksd1 | grep -oE '[^ ]+$' | head -n1
Produce the same results for me as 
df | grep /dev/cardblksd1 | grep -oE '[^ ]+$'

Which is not surprising since I only return one line on my XS.  All and all this is probably a good thing to have since someone else might have something else mounted on their SDcard or USB and this will result in more than one line matching /dev/????? SDcard/USB.  Fortunately it appears as if the root mount of those device seems to be returning the first line so it's good to have in the code to avoid issues like you have.

Thanks a lot for your inputs and fixes.
