### ISSUE TITLE
"returning" from the firmware list

### ISSUE THREAD

**Issue by aasoror** [snappy46/Pivos-Firmware-Install-Addon#4]
Just nitpicking, if you open the addon then press "return/back" instead of actually selecting a firmware from the list, you will get the "do you really want to install ?" prompt as if you actually selected one from the list.

**Comment by snappy46** [comment]
Thank you for reporting.
Issue fix with commit# 4706f7c5fa2f52cbde46dfb74933caa41b263b7c .  Script now just quit if no selection is made.
